### PR TITLE
fix: Allow octal escapes with 1 to 3 digits

### LINKED ISSUE #270: bug: Octal escapes sequences with less than 3 digits are NOT parsed as `escape_sequence`
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-python

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

_No response_

### Describe the bug

Octal escape sequences are defined in the grammar as `/\d{3}/`, but the [python documentation](https://docs.python.org/3/reference/lexical_analysis.html#escape-sequences) states that:

> 2. As in Standard C, **up to three** octal digits are accepted.

Meaning that 3 is the maximum, not the required amount. Easy test:

```python
>>> '\1' == '\01' == '\001'
True
```

### Steps To Reproduce/Bad Parse Tree

```python
'\1'
'\01'
'\001'
```

```query
(module [0, 0] - [3, 0]
  (expression_statement [0, 0] - [0, 4]
    (string [0, 0] - [0, 4]
      (string_start [0, 0] - [0, 1])
      (string_content [0, 1] - [0, 3])
      (string_end [0, 3] - [0, 4])))
  (expression_statement [1, 0] - [1, 5]
    (string [1, 0] - [1, 5]
      (string_start [1, 0] - [1, 1])
      (string_content [1, 1] - [1, 4])
      (string_end [1, 4] - [1, 5])))
  (expression_statement [2, 0] - [2, 6]
    (string [2, 0] - [2, 6]
      (string_start [2, 0] - [2, 1])
      (string_content [2, 1] - [2, 5]
        (escape_sequence [2, 1] - [2, 5]))
      (string_end [2, 5] - [2, 6]))))
```

### Expected Behavior/Parse Tree

```query
(module [0, 0] - [3, 0]
  (expression_statement [0, 0] - [0, 4]
    (string [0, 0] - [0, 4]
      (string_start [0, 0] - [0, 1])
      (string_content [0, 1] - [0, 3]
        (escape_sequence [0, 1] - [0, 3]))
      (string_end [0, 3] - [0, 4])))
  (expression_statement [1, 0] - [1, 5]
    (string [1, 0] - [1, 5]
      (string_start [1, 0] - [1, 1])
      (string_content [1, 1] - [1, 4]
        (escape_sequence [1, 1] - [1, 4]))
      (string_end [1, 4] - [1, 5])))
  (expression_statement [2, 0] - [2, 6]
    (string [2, 0] - [2, 6]
      (string_start [2, 0] - [2, 1])
      (string_content [2, 1] - [2, 5]
        (escape_sequence [2, 1] - [2, 5]))
      (string_end [2, 5] - [2, 6]))))
```

### Repro

```Python
'\1'
'\01'
'\001'
```

### PR DESCRIPTION
**Pull request by ValdezFOmar**
Fix #270

### CODE REVIEW

**Comment by amaanq** [comment]
nice, thank you! just one *minor* comment (for styling really)

File: bindings/rust/build.rs [hunk 1]
```diff
@@ -3,6 +3,9 @@ fn main() {
 
     let mut c_config = cc::Build::new();
     c_config.include(src_dir);
+    #[cfg(target_env = "msvc")]
+    c_config.flag("-utf-8");
+
```
Comment (amaanq) [inline bindings/rust/build.rs:8]:
```suggestion

    #[cfg(target_env = "msvc")]
    c_config.flag("-utf-8");

```

**Comment by amaanq** [comment]
thanks!
